### ISSUE TITLE
Documentation for "pMode" parameter field of Kriging module looks wrong

### ISSUE THREAD

**Issue by rafaelalmeida** [moovida/jgrasstools#10]
In the Javadoc for this field, [it is said](https://github.com/moovida/jgrasstools/blob/56e8fe50de7647cb579a9b28363842353ec20e13/hortonmachine/src/main/java/org/jgrasstools/hortonmachine/modules/statistics/kriging/OmsKriging.java#L131) that the value can be 0, 1, 2 or 3. However, in the very beginning of verifyInput() [only values 0 or 1 are accepted](https://github.com/moovida/jgrasstools/blob/56e8fe50de7647cb579a9b28363842353ec20e13/hortonmachine/src/main/java/org/jgrasstools/hortonmachine/modules/statistics/kriging/OmsKriging.java#L491).

This is a bit confusing, especially because the semantics for pMode == 1 seems to be reversed: Javadoc says it means irregular grid, while the rest of the source seems to mean regular grid.

I can submit a Pull Request myself to fix this, if my understanding is correct. Is it?

*Edit: correcting values*

**Comment by moovida** [comment]
Hi @rafaelalmeida , thanks for this. Yes, the 4 modes were originally available but when the port was done 2 of them didn't seem to make much sense. The original authors never decided to contribute the rest, so I agree with you, it is better to remove them. The javadoc is still an old copy/paste. 

A pull request would be much appreciated, thanks.

**Comment by moovida** [comment]
merged in
